version: "3.7"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "test"

  webpacker:
    build: .
    volumes:
      - .:/app
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - node_modules:/app/node_modules
    command:
      - /bin/sh
      - -c
      - yarn install && ./bin/webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
  rails:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - node_modules:/app/node_modules
    command: start.sh
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
      DATABASE_HOST: db
volumes:
  db:
    driver: local
  bundle:
    driver: local
  yarn-cache:
  node_modules:
